docs: Fix typos
AnonymouX47/term-image pull request #98
Opened 2023-07-20 23:06 UTC by kianmeng

Found via `codespell`

2023-07-20 23:55 UTC, AnonymouX47 commented
Thanks so much, I'll review this soon.

2023-09-29 19:11 UTC, AnonymouX47 requested changes
Sorry it took me so long :( , I've been busy with #97.

Gone through all the changes. There's only one I found to be incorrect. Also, there are now conflicts.

Let me know if you're willing to make the necessary changes for a merge or not. If not, it's all okay :) , I'll handle them and merge locally.

Thanks.

2023-09-30 05:54 UTC, kianmeng commented
@AnonymouX47 Done.

2023-09-30 07:42 UTC, AnonymouX47 requested changes
Thanks for adding in the new files.

I think most, if not all, of the changes I requested here will require manual correction.

Again, I'm totally fine with handling them. So, let me know if you'd prefer that.

If you would be handling them, I'll recommend you don't force-push this time :smiley:. I understand it was the simplest way out earlier due to the conflicts but it isn't always the best and I don't think it's necessary for these set of changes.

Thanks once again :smiley:.

2023-09-30 07:42 UTC, AnonymouX47 commented on CONTRIBUTING.md
> +  - **sorted** (preferably lexicographically, with the exception of dependent definitions e.g decorators, metaclasses, baseclasses, etc)
Note to self: dependent -> depended-upon

2023-09-30 07:42 UTC, AnonymouX47 commented on docs/source/api/image.rst
>  ^^^^^^^^^^^^^^
I missed this earlier, reST specifies that the underline (^^^...) be at least, as long as the section title.

Due to this, the docs are failing to build.

2023-09-30 07:42 UTC, AnonymouX47 commented on src/term_image/renderable/_renderable.py
> +                ``render_size.height - 1`` occurrences of ``\\n`` (the newline sequence).
This makes the line length 89 (> 88) and causes the lint check to fail. The line will require rewrapping.

2023-09-30 07:42 UTC, AnonymouX47 commented on tests/renderable/test_types.py
> +    def test_inequality(self, args1, args2):
"unequality" here is deliberate.

2023-09-30 07:42 UTC, AnonymouX47 commented on tests/test_padding.py
> +    def test_inequality(self, args1, kwargs1, args2, kwargs2):
"unequality" here is deliberate.

2023-09-30 07:42 UTC, AnonymouX47 commented on tests/test_padding.py
> +    def test_inequality(self, args1, kwargs1, args2, kwargs2):
"unequality" here is deliberate.

2023-10-01 06:12 UTC, AnonymouX47 approved these changes
Thanks so much :heart:

2023-10-01 06:13 UTC, merged

2023-10-01 06:17 UTC, kianmeng commented
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face: